# Generated by Django 4.1.3 on 2022-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pic')),
                ('discount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('person', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
